server:
  port: 8081

spring:
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-name: clinic
      cluster-nodes: 127.0.0.1:9300
  mvc:
    servlet:
      load-on-startup: 1
  datasource: #数据库配置信息，属于spring
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clinic?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456



mybatis:
  mapper-locations: classpath:mapper/*.xml # 设置mybatis的静态资源位置，就是它的xml配置文件
  type-aliases-package: com.hcc.pojo #设置实体类的别名，告诉框架去哪里找实体类
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名法
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印sql
      # 还有一个mapper接口类的位置也要告诉SpringBoot，但不在这里配置，在启动类里面加一个mapperScan注解

